### ISSUE TITLE
Access-Control headers settings

### ISSUE THREAD

**Issue by wakatanka** [360works/fmangular#4]
Hi, can you provide some info how to set this access-control parameter and where?

thanks so much

**Comment by shmert** [comment]
The following response headers should be set:

    Access-Control-Allow-Origin: the base URL for your application
    Access-Control-Allow-Headers: the Access-Control-Request-Headers request header
    Access-Control-Allow-Methods: the Access-Control-Request-Method request header

You will also want to set the following to allow cookies and auth.

    Access-Control-Allow-Credentials: true

Note that you cannot do this if using a wildcard * for `Access-Control-Allow-Origin`. 

Some instructions on setting up various web servers are here: http://enable-cors.org/server.html

**Comment by shmert** [comment]
I just tested this out with apache. 

Edit the file at `/Library/FileMaker Server/HTTPServer/conf/httpd.conf`

Add the following headers, replacing `Header set Access-Control-Allow-Origin` host with your own value:

    Header set Access-Control-Allow-Origin "http://fez.local"
    Header set Access-Control-Allow-Headers "accept, authorization, *"
    Header set Access-Control-Allow-Credentials "true"

Restart FileMaker's apache instance:

`sudo /Library/FileMaker Server/HTTPServer/bin/httpdctl restart`

Also, upgrade to the latest FMAngular (0.1.0), which includes a fix for passing auth in POST requests.

Instructions for IIS are welcome, the headers set will be identical to these.
