### ISSUE TITLE
fmangular not working with FileMaker Server 14 nor 15?

### ISSUE THREAD

**Issue by iiicareer** [360works/fmangular#5]
We've successfully deployed fmangular app using FMS13, but seems to be not working on FMS14 nor 15. Do you happen to know any issues with the newer versions of FileMaker?

**Comment by shmert** [comment]
Not aware of issues, what sort of error are you getting?

**Comment by iiicareer** [comment]
Hello shmert,

Thank you for your response. It turned out it was the same issue with the Access-Control headers setting and the firewall as described on your previous question. Sorry for the trouble and thanks for taking the time!
