### ISSUE TITLE
Rewrite or update for Angular?

### ISSUE THREAD

**Issue by mw777eds** [360works/fmangular#6]
Since Angular2+ is so different, have you considered updating this to work with the current version of Angular?

**Comment by jvincilione** [comment]
@mw777rcc You want to tackle doing that as a separate open source project?

**Comment by shmert** [comment]
I haven't given it much thought, as I'm still primarily using angular 1 for projects.

**Comment by mw777eds** [comment]
I don't have time right now but I may do it in the future.  I use Angular 4 and don't use AngularJS anymore.
